#!/bin/sh

aws cloudformation create-stack \
  --stack-name transcribro-stack \
  --template-body file://cloudformation.yml \
  # must be deployed in us-east-1 for cloudfront cdn
  --region us-east-1

# aws cloudformation create-stack \
#   --stack-name transcribro-stack \
#   --template-body file://cloudformation.yml \
#   # closer to texas
#   --region us-east-2